# FreePDFImport - SVG Document Parser
# Copyright (C) 2026 hiratazx
# License: GPL-3.0
#
# Parses SVG files generated by pdftocairo using Ruby's built-in REXML.
# Extracts all vector elements and converts them to point arrays.

require 'rexml/document'
require_relative 'path_parser'
require_relative 'utils'

module FreePDFImport
  module SVGParser
    # Parsed SVG result
    SVGData = Struct.new(:width, :height, :view_box, :paths)

    # A single parsed path with metadata
    ParsedPath = Struct.new(:points, :closed, :stroke, :fill, :stroke_width, :transform)

    # Parse an SVG file and return all paths as point arrays
    # Returns an SVGData struct
    def self.parse_file(svg_path, curve_tolerance = 0.5)
      unless File.exist?(svg_path)
        raise "SVG file not found: #{svg_path}"
      end

      svg_content = File.read(svg_path)
      parse_string(svg_content, curve_tolerance)
    end

    # Parse an SVG string
    def self.parse_string(svg_string, curve_tolerance = 0.5)
      doc = REXML::Document.new(svg_string)
      root = doc.root

      unless root
        raise "Invalid SVG: no root element"
      end

      # Extract document dimensions
      width = parse_length(root.attributes['width'] || '0')
      height = parse_length(root.attributes['height'] || '0')

      # Parse viewBox if present
      view_box = nil
      if root.attributes['viewBox']
        vb = root.attributes['viewBox'].split(/[\s,]+/).map(&:to_f)
        view_box = { min_x: vb[0], min_y: vb[1], width: vb[2], height: vb[3] } if vb.length == 4

        # If width/height are zero, use viewBox dimensions
        if width == 0 && view_box
          width = view_box[:width]
        end
        if height == 0 && view_box
          height = view_box[:height]
        end
      end

      # Parse all vector elements recursively
      paths = []
      parse_element(root, paths, curve_tolerance, [])

      Utils.log("Parsed SVG: #{width}x#{height}, #{paths.length} path(s)")
      SVGData.new(width, height, view_box, paths)
    end

    private

    # Recursively parse SVG elements
    def self.parse_element(element, paths, curve_tolerance, parent_transforms)
      # Collect transforms for this element
      transforms = parent_transforms.dup
      if element.attributes['transform']
        transforms << parse_transform(element.attributes['transform'])
      end

      element.each_element do |child|
        case child.name
        when 'path'
          parse_path_element(child, paths, curve_tolerance, transforms)
        when 'line'
          parse_line_element(child, paths, transforms)
        when 'polyline'
          parse_polyline_element(child, paths, false, transforms)
        when 'polygon'
          parse_polyline_element(child, paths, true, transforms)
        when 'rect'
          parse_rect_element(child, paths, transforms)
        when 'circle'
          parse_circle_element(child, paths, curve_tolerance, transforms)
        when 'ellipse'
          parse_ellipse_element(child, paths, curve_tolerance, transforms)
        when 'g', 'svg', 'defs', 'clipPath', 'symbol', 'use'
          # Recurse into group-like elements
          parse_element(child, paths, curve_tolerance, transforms)
        end
      end
    end

    # Parse a <path> element
    def self.parse_path_element(element, paths, curve_tolerance, transforms)
      d = element.attributes['d']
      return if d.nil? || d.strip.empty?

      stroke = element.attributes['stroke'] || extract_style_prop(element, 'stroke')
      fill = element.attributes['fill'] || extract_style_prop(element, 'fill')
      stroke_width = element.attributes['stroke-width'] || extract_style_prop(element, 'stroke-width') || '1'

      subpaths = PathParser.parse(d, curve_tolerance)

      subpaths.each do |subpath|
        next if subpath.length < 2

        # Apply transforms
        transformed_points = apply_transforms(subpath, transforms)

        # Determine if path is closed
        closed = subpath.respond_to?(:closed?) && subpath.closed?

        paths << ParsedPath.new(
          transformed_points,
          closed,
          stroke,
          fill,
          stroke_width.to_f,
          nil
        )
      end
    end

    # Parse a <line> element
    def self.parse_line_element(element, paths, transforms)
      x1 = (element.attributes['x1'] || '0').to_f
      y1 = (element.attributes['y1'] || '0').to_f
      x2 = (element.attributes['x2'] || '0').to_f
      y2 = (element.attributes['y2'] || '0').to_f

      points = apply_transforms([[x1, y1], [x2, y2]], transforms)
      paths << ParsedPath.new(points, false, nil, nil, 1.0, nil)
    end

    # Parse a <polyline> or <polygon> element
    def self.parse_polyline_element(element, paths, closed, transforms)
      points_str = element.attributes['points']
      return if points_str.nil? || points_str.strip.empty?

      # Parse pairs of coordinates
      nums = points_str.scan(/[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?/).map(&:to_f)
      points = []
      i = 0
      while i < nums.length - 1
        points << [nums[i], nums[i + 1]]
        i += 2
      end

      return if points.length < 2

      # Close polygon
      if closed && points.length > 2
        first = points.first
        last = points.last
        unless (first[0] - last[0]).abs < 0.001 && (first[1] - last[1]).abs < 0.001
          points << [first[0], first[1]]
        end
      end

      points = apply_transforms(points, transforms)
      paths << ParsedPath.new(points, closed, nil, nil, 1.0, nil)
    end

    # Parse a <rect> element
    def self.parse_rect_element(element, paths, transforms)
      x = (element.attributes['x'] || '0').to_f
      y = (element.attributes['y'] || '0').to_f
      w = (element.attributes['width'] || '0').to_f
      h = (element.attributes['height'] || '0').to_f

      return if w < 0.001 || h < 0.001

      # TODO: Handle rx/ry for rounded corners
      points = [
        [x, y],
        [x + w, y],
        [x + w, y + h],
        [x, y + h],
        [x, y]  # Close
      ]

      points = apply_transforms(points, transforms)
      paths << ParsedPath.new(points, true, nil, nil, 1.0, nil)
    end

    # Parse a <circle> element
    def self.parse_circle_element(element, paths, curve_tolerance, transforms)
      cx = (element.attributes['cx'] || '0').to_f
      cy = (element.attributes['cy'] || '0').to_f
      r = (element.attributes['r'] || '0').to_f

      return if r < 0.001

      # Approximate circle with segments
      n_segs = calculate_circle_segments(r, curve_tolerance)
      points = []
      (0..n_segs).each do |i|
        angle = 2.0 * Math::PI * i.to_f / n_segs.to_f
        px = cx + r * Math.cos(angle)
        py = cy + r * Math.sin(angle)
        points << [px, py]
      end

      points = apply_transforms(points, transforms)
      paths << ParsedPath.new(points, true, nil, nil, 1.0, nil)
    end

    # Parse an <ellipse> element
    def self.parse_ellipse_element(element, paths, curve_tolerance, transforms)
      cx = (element.attributes['cx'] || '0').to_f
      cy = (element.attributes['cy'] || '0').to_f
      rx = (element.attributes['rx'] || '0').to_f
      ry = (element.attributes['ry'] || '0').to_f

      return if rx < 0.001 || ry < 0.001

      max_r = [rx, ry].max
      n_segs = calculate_circle_segments(max_r, curve_tolerance)
      points = []
      (0..n_segs).each do |i|
        angle = 2.0 * Math::PI * i.to_f / n_segs.to_f
        px = cx + rx * Math.cos(angle)
        py = cy + ry * Math.sin(angle)
        points << [px, py]
      end

      points = apply_transforms(points, transforms)
      paths << ParsedPath.new(points, true, nil, nil, 1.0, nil)
    end

    # Calculate number of segments for circle approximation
    def self.calculate_circle_segments(radius, tolerance)
      if radius < 1.0
        return 12
      end
      # n = pi / acos(1 - tolerance/radius)
      ratio = tolerance / radius
      ratio = [ratio, 0.99].min
      n = (Math::PI / Math.acos(1.0 - ratio)).ceil
      [[n, 8].max, 72].min
    end

    # Parse SVG length value (may include units)
    def self.parse_length(value)
      return 0.0 if value.nil? || value.empty?
      # Strip units like px, pt, mm, cm, in
      if value =~ /^([+-]?[\d.]+)\s*(px|pt|mm|cm|in)?$/i
        num = $1.to_f
        unit = ($2 || 'px').downcase
        case unit
        when 'pt'
          num  # Keep as points
        when 'mm'
          num * 72.0 / 25.4
        when 'cm'
          num * 72.0 / 2.54
        when 'in'
          num * 72.0
        else
          num  # px and default
        end
      else
        value.to_f
      end
    end

    # Extract a CSS property from an element's style attribute
    def self.extract_style_prop(element, prop_name)
      style = element.attributes['style']
      return nil unless style
      style.split(';').each do |declaration|
        parts = declaration.split(':').map(&:strip)
        return parts[1] if parts[0] == prop_name && parts.length >= 2
      end
      nil
    end

    # Parse SVG transform attribute
    # Returns a 3x3 matrix as a flat array [a, b, c, d, e, f]
    # where the matrix is: | a c e |
    #                      | b d f |
    #                      | 0 0 1 |
    def self.parse_transform(transform_str)
      # Start with identity matrix
      result = [1, 0, 0, 1, 0, 0]

      # Match each transform function
      transform_str.scan(/(matrix|translate|scale|rotate|skewX|skewY)\s*\(([^)]+)\)/i) do |func, args|
        values = args.scan(/[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?/).map(&:to_f)

        case func.downcase
        when 'matrix'
          if values.length >= 6
            result = multiply_matrices(result, values[0..5])
          end
        when 'translate'
          tx = values[0] || 0
          ty = values[1] || 0
          result = multiply_matrices(result, [1, 0, 0, 1, tx, ty])
        when 'scale'
          sx = values[0] || 1
          sy = values[1] || sx
          result = multiply_matrices(result, [sx, 0, 0, sy, 0, 0])
        when 'rotate'
          angle = (values[0] || 0) * Math::PI / 180.0
          cos_a = Math.cos(angle)
          sin_a = Math.sin(angle)
          if values.length >= 3
            # Rotate around point (cx, cy)
            cx = values[1]
            cy = values[2]
            result = multiply_matrices(result, [1, 0, 0, 1, cx, cy])
            result = multiply_matrices(result, [cos_a, sin_a, -sin_a, cos_a, 0, 0])
            result = multiply_matrices(result, [1, 0, 0, 1, -cx, -cy])
          else
            result = multiply_matrices(result, [cos_a, sin_a, -sin_a, cos_a, 0, 0])
          end
        when 'skewx'
          angle = (values[0] || 0) * Math::PI / 180.0
          result = multiply_matrices(result, [1, 0, Math.tan(angle), 1, 0, 0])
        when 'skewy'
          angle = (values[0] || 0) * Math::PI / 180.0
          result = multiply_matrices(result, [1, Math.tan(angle), 0, 1, 0, 0])
        end
      end

      result
    end

    # Multiply two 2D affine transformation matrices
    # Each matrix is [a, b, c, d, e, f]
    def self.multiply_matrices(m1, m2)
      [
        m1[0] * m2[0] + m1[2] * m2[1],
        m1[1] * m2[0] + m1[3] * m2[1],
        m1[0] * m2[2] + m1[2] * m2[3],
        m1[1] * m2[2] + m1[3] * m2[3],
        m1[0] * m2[4] + m1[2] * m2[5] + m1[4],
        m1[1] * m2[4] + m1[3] * m2[5] + m1[5]
      ]
    end

    # Apply a chain of transforms to a set of points
    def self.apply_transforms(points, transforms)
      return points if transforms.empty?

      # Compose all transforms into a single matrix
      combined = [1, 0, 0, 1, 0, 0]
      transforms.each do |t|
        combined = multiply_matrices(combined, t)
      end

      # Apply to each point
      points.map do |pt|
        x = combined[0] * pt[0] + combined[2] * pt[1] + combined[4]
        y = combined[1] * pt[0] + combined[3] * pt[1] + combined[5]
        [x, y]
      end
    end
  end
end
